### ISSUE TITLE
Can't open the sample project in Unity.

### ISSUE THREAD

**Issue by AONYA-LU** [singaporetech/immersification-wip-locomotion#6]
Hey there,
When I was trying to load the sample project, the following error was encountered. 

<img width="566" alt="Screenshot 2023-07-27 183857" src="https://github.com/singaporetech/immersification-wip-locomotion/assets/136964404/e4ce6f04-779d-477c-a2c9-7ad0aeee0e43">

Does anyone know what the problem is and how do I solve it ?

**Comment by songjia** [comment]
Hi @AONYA-LU, which version of Unity did you use to load the project?

**Comment by AONYA-LU** [comment]
> Hi @AONYA-LU, which version of Unity did you use to load the project?

Hi, @songjia  Thanks a lot for replaying!

I've tried 2022.3.0f1c1,  2020.3.6f1c1 and 2020.3.6f1. They all ran into the same error.


and everytime when I try to open a new one, I get the following: 
<img width="566" alt="Screenshot 2023-07-27 183857" src="https://github.com/singaporetech/immersification-wip-locomotion/assets/136964404/85be9890-8b57-4b66-86b2-d6dc647c3b3a">

I can solve this one by deleting the ArtifactDB file, but I'm not sure am I supposed to do that...

**Comment by LeonFooC** [comment]
Hi @AONYA-LU, thanks for highlighting this to us. I believe this may be because the version of the High Definition Render Pipeline (HDRP) package for the project and the version Unity Editor is trying to use are different. The project was built using HDRP v10.5.0, which according to Unity's documentation is only supported between Unity Editor versions 2020.2 till 2020.3. I believe the editor is trying to use HDRP v14.0.7.

When you tried opening with v2020.3.6f1 did you try it on a new copy of the project, or did you try opening a copy that had already attempted to be opened with another Unity version? If it's the latter, I think Unity probably updated some package and library files, so the error might still persist even when opening using v2020.3.6f1, which is the version used to create the sample unity project. 

You can try opening a new copy project with Unity Editor v2020.3.6f1, maybe that will help?

**Comment by songjia** [comment]
@AONYA-LU, I've updated the package file with the release v1.1.4 from value software.
I can open the project with Unity v2020.3.6f1, as @LeonFooC mentioned.

Could you please switch to the branch `fix-openvr-package-loading` and have an other try?

**Comment by songjia** [comment]
@AONYA-LU, I've removed the cached temporary Unity files in this branch.
Please run:
```
git clean -Xdf
```
to remove the temp files for a fresh loading.

**Comment by AONYA-LU** [comment]
@songjia @LeonFooC  
Thanks a lot for the help!
The sample project can be successfully opened now.
